@WebApplication1_HostAddress = http://localhost:443

GET {{WebApplication1_HostAddress}}/api/products/
Accept: application/json

###
GET {{WebApplication1_HostAddress}}/api/product/5/
Accept: application/json

###
POST {{WebApplication1_HostAddress}}/api/products/
Content-Type: application/json

###
PUT {{WebApplication1_HostAddress}}/api/products/{{id}}/
Content-Type: application/json

###
DELETE {{WebApplication1_HostAddress}}/api/products/{{id}}/
Accept: application/json